services:
  - type: web
    name: restaurant-wishlist
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_USER
        sync: false
      - key: MONGO_PASSWORD
        sync: false
      - key: MONGO_CLUSTER
        sync: false
      - key: MONGO_DB
        sync: false
